{
 "title": "AWS overview",
 "time": { "from": "now-30d", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "experiment",
    "label": "experiment",
    "query": "{\"find\": \"terms\", \"field\": \"run.keyword\"}"
   },
   {
    "name": "user",
    "label": "user",
    "query": "{\"find\": \"terms\", \"field\": \"userIdentity.userName.keyword\"}"
   },
   { "name": "Filters" },
   {
    "name": "event_type",
    "label": "Event type",
    "query": "{\"find\": \"terms\", \"field\": \"eventName.keyword\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Action attempts $experiment: $user",
   "type": "stat",
   "gridPos": { "h": 8, "w": 5, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: $event_type",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS event: RunInstances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 4, "x": 5, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: RunInstances",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS event: DescribeInstances",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: DescribeInstances",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS event: DescribeVpcs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: DescribeVpcs",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS event: DescribeSubnets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: DescribeSubnets",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS event: DescribeHosts",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: DescribeHosts",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "AWS events: S3 Buckets",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: GetBucket*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: Boto",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: Boto*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: aws-cli",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 3, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: aws-cli*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: aws-sdk-nodejs",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 6, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: aws-sdk-nodejs*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: aws-sdk-dotnet",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 9, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: aws-sdk-dotnet*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: ElasticWolf",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: ElasticWolf*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "UserAgent: aws-sdk-go",
   "type": "stat",
   "gridPos": { "h": 8, "w": 3, "x": 15, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "auto", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND userAgent.keyword: aws-sdk-go*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Time Europe/Amsterdam",
   "type": "grafana-clock-panel",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 8 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Panel Title",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "eventName.keyword",
       "id": "2",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      {
       "field": "eventName.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Data $experiment: $user",
   "type": "table",
   "gridPos": { "h": 20, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": { "size": 500 },
       "type": "raw_data"
      }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment AND eventName.keyword: $event_type",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Locations $experiment: $user",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 29, "w": 24, "x": 0, "y": 44 },
   "valueName": "current",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "geoip.city_name.keyword",
       "id": "3",
       "settings": { "min_doc_count": 0, "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      { "field": "geoip.location", "id": "2", "settings": { "precision": 3 }, "type": "geohash_grid" }
     ],
     "metrics": [
      {
       "field": "select field",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "userIdentity.userName.keyword:$user AND run.keyword:$experiment",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}